services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: db_testcontainers_jdbc
      POSTGRES_PASSWORD: magadiflo
      POSTGRES_USER: magadiflo
    ports:
      - 5433:5432